import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check } from 'lucide-react';

const plans=[
 {name:'Essencial',price:'79,90',text:'Para profissionais que estão estruturando o primeiro atendimento.',items:['1 profissional','50 atendimentos por mês','Agenda e organização de casos']},
 {name:'Profissional',price:'129,90',text:'Para quem deseja transformar o atendimento em uma operação organizada.',items:['1 profissional','200 atendimentos por mês','Fluxos personalizados'],featured:true},
 {name:'Equipe',price:'499,90',text:'Para clínicas, escritórios e equipes multidisciplinares.',items:['Até 10 profissionais','1.000 atendimentos por mês','Gestão de equipe e analytics']}
];
export default function PricingPage(){return <main className="pricing-page"><header className="pricing-header"><Link href="/" className="pricing-brand" aria-label="CasoZero"><span/></Link><Link href="/" className="text-action"><ArrowLeft size={15}/> Voltar à apresentação</Link></header><section className="pricing-hero"><p className="eyebrow">Planos simples e transparentes</p><h1>Uma base para organizar<br/>cada novo atendimento.</h1><p>Comece com o plano adequado ao seu momento e evolua sem trocar de plataforma.</p></section><section className="pricing-grid">{plans.map(plan=><article className={`pricing-card ${plan.featured?'featured':''}`} key={plan.name}>{plan.featured&&<span className="pricing-tag">Mais escolhido</span>}<h2>{plan.name}</h2><p>{plan.text}</p><div className="pricing-value"><small>R$</small><strong>{plan.price}</strong><span>/mês</span></div><ul>{plan.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><Link href="/app" className={plan.featured?'primary full':'secondary full'}>Começar agora <ArrowRight size={15}/></Link></article>)}</section><p className="pricing-note">Todos os planos poderão ser adaptados a advocacia, psicologia, fisioterapia, arquitetura e outras áreas profissionais.</p></main>}
