'use client';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, Loader2 } from 'lucide-react';
import { useState } from 'react';

const plans=[
 {id:'caso_zero',name:'CasoZero',price:'0,00',text:'Para começar a organizar seus primeiros atendimentos.',items:['1 profissional','5 atendimentos por mês','Casos','Pendências','Agenda']},
 {id:'caso_um',name:'CasoUm',price:'69,90',text:'Para profissionais que estão estruturando o primeiro atendimento.',items:['1 profissional','20 atendimentos por mês','Casos','Pendências','Agenda']},
 {id:'caso_dois',name:'CasoDois',price:'119,90',text:'Para transformar o atendimento em uma operação organizada.',items:['1 profissional','100 atendimentos por mês','Casos','Pendências','Agenda','Analytics'],featured:true},
 {id:'caso_tres',name:'CasoTrês',price:'299,90',text:'Para profissionais que precisam de equipe e visão completa.',items:['Até 10 profissionais','300 atendimentos por mês','Casos','Pendências','Agenda','Analytics','Equipe']}
];
export default function PricingPage(){const [loading,setLoading]=useState('');const [error,setError]=useState('');const checkout=async(id:string)=>{if(id==='caso_zero'){window.location.href='/cadastro';return}setLoading(id);setError('');try{const response=await fetch('/api/stripe/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:id})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível iniciar o checkout.');if(data.url)window.location.href=data.url;else throw new Error('A Stripe não retornou o checkout.')}catch(e){setError(e instanceof Error?e.message:'Erro ao iniciar pagamento.');setLoading('')}};return <main className="pricing-page"><header className="pricing-header"><Link href="/" className="pricing-back"><ArrowLeft size={15}/> Voltar à apresentação</Link></header><section className="pricing-hero"><p className="eyebrow">Planos simples e transparentes</p><h1>Uma base para organizar<br/>cada novo atendimento.</h1><p>Comece com o plano adequado ao seu momento e evolua sem trocar de plataforma.</p></section><section className="pricing-grid">{plans.map(plan=><article className={`pricing-card ${plan.featured?'featured':''}`} key={plan.id}>{plan.featured&&<span className="pricing-tag">Mais escolhido</span>}<h2>{plan.name}</h2><p>{plan.text}</p><div className="pricing-value"><small>R$</small><strong>{plan.price}</strong><span>/mês</span></div><ul>{plan.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><button onClick={()=>checkout(plan.id)} disabled={Boolean(loading)} className={plan.featured?'primary full':'secondary full'}>{loading===plan.id?<><Loader2 size={15} className="spin"/> Abrindo checkout...</>:<>Começar agora <ArrowRight size={15}/></>}</button></article>)}</section>{error&&<p className="pricing-error">{error}</p>}<p className="pricing-note">Todos os planos poderão ser adaptados a advocacia, psicologia, fisioterapia, arquitetura e outras áreas profissionais.</p></main>}
