'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, FileText, Loader2, MessageCircle, Paperclip, RotateCcw } from 'lucide-react';
import { lawyer } from '@/mocks/data';
import { mockAIService } from '@/services/ai';
import { casesService } from '@/services/cases';
import { AIInterviewState, InterviewMessage, LegalCase } from '@/types';
const draftKey='casozero-interview-draft';
export default function Interview(){
 const [stage,setStage]=useState<'welcome'|'chat'|'done'>('welcome'); const [consent,setConsent]=useState(false); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [state,setState]=useState<AIInterviewState>({step:0,facts:{},alreadyAsked:[]});
 const [messages,setMessages]=useState<InterviewMessage[]>([{id:'start',role:'assistant',content:'Para começar, conte em poucas palavras o que aconteceu.',createdAt:'Agora'}]);
 useEffect(()=>{const d=localStorage.getItem(draftKey);if(d){try {const p=JSON.parse(d);setMessages(p.messages);setState(p.state);setStage('chat')}catch{}}},[]);
 useEffect(()=>{if(stage==='chat')localStorage.setItem(draftKey,JSON.stringify({messages,state}));},[messages,state,stage]);
 const progress=Math.min(88,18+state.step*14); const hint=state.step<2?'Entendendo seu caso':state.step<5?'Organizando informações':'Quase concluído';
 function begin(){if(consent)setStage('chat');}
 async function send(value=input){if(!value.trim()||loading)return;const user={id:crypto.randomUUID(),role:'user' as const,content:value,createdAt:'Agora'};setMessages(x=>[...x,user]);setInput('');setLoading(true);await new Promise(r=>setTimeout(r,550));const reply=mockAIService.reply(value,state);setState(reply.state);setMessages(x=>[...x,{id:crypto.randomUUID(),role:'assistant',content:reply.message,createdAt:'Agora'}]);setLoading(false);if(reply.action==='finish_interview')setTimeout(()=>finish(reply.state),700);}
 function finish(finalState:AIInterviewState){const id=Date.now().toString();const created:LegalCase={id,code:`CZ-2026-${String(Math.floor(Math.random()*900+100)).padStart(5,'0')}`,name:'Novo pré-atendimento',area:finalState.area||'Trabalhista',topics:['Tema para análise'],status:'new',compatibility:'Alta',createdAt:'Agora',summary:'Segundo o relato informado, o potencial cliente descreveu uma situação que foi organizada para análise do escritório.',documents:[],missing:['Documentos comprobatórios, se disponíveis.'],messages};casesService.add(created);localStorage.removeItem(draftKey);setStage('done');}
 if(stage==='welcome') return <main className="public-shell"><section className="public-card welcome"><div className="brand-mark">CZ</div><p className="eyebrow">{lawyer.firm}</p><h1>Pré-atendimento<br/>inteligente.</h1><p className="lead">Conte rapidamente o que aconteceu. O CasoZero organiza as informações antes da análise do escritório.</p><div className="time"><MessageCircle size={17}/> Leva aproximadamente 3 minutos</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Concordo que as informações fornecidas sejam utilizadas pelo escritório para análise deste pré-atendimento.</span></label><button className="primary" disabled={!consent} onClick={begin}>Começar pré-atendimento <ArrowRight size={18}/></button><p className="fineprint">Este atendimento não substitui orientação jurídica profissional.<br/><a href="#">Política de Privacidade</a> · <a href="#">Termos de Uso</a></p></section></main>;
 if(stage==='done') return <main className="public-shell"><section className="public-card completion"><div className="success"><Check size={30}/></div><p className="eyebrow">Pré-atendimento enviado</p><h1>Pronto! Organizamos as principais informações do seu relato.</h1><p className="lead">Seu pré-atendimento foi encaminhado para análise do escritório. Caso necessário, entraremos em contato.</p><div className="case-code">CZ-2026-00{Math.floor(Math.random()*900+100)}</div><button className="secondary" onClick={()=>setStage('welcome')}>Finalizar</button><p className="fineprint">O CasoZero é uma ferramenta de organização e não fornece aconselhamento jurídico.</p></section></main>;
 return <main className="chat-shell"><header className="chat-header"><div><div className="avatar">CZ</div><div><strong>CasoZero</strong><span>{lawyer.firm}</span></div></div><Link href="/app">Área do advogado</Link></header><section className="chat"><div className="progress"><span>{hint}</span><i><b style={{width:`${progress}%`}}/></i></div><div className="messages">{messages.map(m=><div key={m.id} className={`bubble ${m.role}`}><p>{m.content}</p><small>{m.createdAt}</small></div>)}{loading&&<div className="bubble assistant thinking"><Loader2 size={16}/> Organizando sua resposta...</div>}</div><div className="composer"><button aria-label="Anexar documento" title="Upload será integrado ao armazenamento seguro"><Paperclip size={20}/></button><input aria-label="Sua resposta" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Digite sua resposta"/><button className="send" onClick={()=>send()} aria-label="Enviar"><ArrowRight size={19}/></button></div><div className="quick"><button onClick={()=>send('Sim')}>Sim</button><button onClick={()=>send('Não')}>Não</button><button onClick={()=>send('Não sei informar')}>Não sei informar</button></div><p className="chat-disclaimer">As informações serão encaminhadas ao escritório para análise. Não há aconselhamento jurídico nesta conversa.</p></section></main>;
}
