'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { usePathname, useSearchParams } from 'next/navigation';
import { ArrowRight, Check, FileText, Loader2, MessageCircle, Paperclip, RotateCcw, Trash2 } from 'lucide-react';
import { lawyer } from '@/mocks/data';
import { mockAIService } from '@/services/ai';
import { casesService } from '@/services/cases';
import { AIInterviewState, InterviewMessage, LegalCase } from '@/types';
const draftKey='casozero-interview-draft';
export default function Interview(){
 const pathname=usePathname(); const params=useSearchParams(); const urlArea=pathname.split('/')[2]; const source=params.get('src') || undefined; const areaMap={trabalhista:'Trabalhista',consumidor:'Consumidor',familia:'Família',previdenciario:'Previdenciário',civel:'Cível',empresarial:'Empresarial'} as Record<string,AIInterviewState['area']>; const [stage,setStage]=useState<'welcome'|'profile'|'chat'|'review'|'done'>('welcome'); const [consent,setConsent]=useState(false); const [profile,setProfile]=useState({name:'',age:'',profession:'',phone:'',company:'',salary:''}); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [state,setState]=useState<AIInterviewState>({step:0,facts:{},alreadyAsked:[],area:areaMap[urlArea]});
 const [messages,setMessages]=useState<InterviewMessage[]>([{id:'start',role:'assistant',content:'Para começar, conte em poucas palavras o que aconteceu.',createdAt:'Agora'}]);
 useEffect(()=>{const d=localStorage.getItem(draftKey);if(d){try {const p=JSON.parse(d);setMessages(p.messages);setState(p.state);setStage('chat')}catch{}}},[]);
 useEffect(()=>{if(stage==='chat')localStorage.setItem(draftKey,JSON.stringify({messages,state}));},[messages,state,stage]);
 const progress=Math.min(88,18+state.step*14); const hint=state.step<2?'Entendendo seu caso':state.step<5?'Organizando informações':'Quase concluído';
 function begin(){if(consent)setStage('profile');}
 function beginInterview(){if(!profile.name||!profile.age||!profile.profession||!profile.phone)return;setState(current=>({...current,facts:{...current.facts,name:profile.name,age:profile.age,profession:profile.profession,phone:profile.phone}}));setMessages([{id:'start',role:'assistant',content:`Olá, ${profile.name.split(' ')[0]}. Para começar, conte em poucas palavras o que aconteceu.`,createdAt:'Agora'}]);setStage('chat');}
 async function send(value=input){if(!value.trim()||loading)return;const user={id:crypto.randomUUID(),role:'user' as const,content:value,createdAt:'Agora'};setMessages(x=>[...x,user]);setInput('');setLoading(true);await new Promise(r=>setTimeout(r,550));const reply=mockAIService.reply(value,state);setState(reply.state);setMessages(x=>[...x,{id:crypto.randomUUID(),role:'assistant',content:reply.message,createdAt:'Agora'}]);setLoading(false);if(reply.action==='finish_interview')setTimeout(()=>setStage('review'),700);}
 function finish(finalState:AIInterviewState){const id=Date.now().toString();const created:LegalCase={id,caseNumber:0,code:`CZ-2026-${String(Math.floor(Math.random()*900+100)).padStart(5,'0')}`,name:profile.name,age:profile.age,profession:profile.profession,phone:profile.phone,company:profile.company,salary:profile.salary,leadSource:source as LegalCase['leadSource'],area:finalState.area||'Trabalhista',topics:['Tema para análise'],status:'new',compatibility:'Alta',createdAt:'Agora',summary:`${profile.name} (${profile.age} anos, ${profile.profession}) relata uma situação que foi organizada para análise do escritório.`,documents:[],missing:['Documentos comprobatórios, se disponíveis.'],messages};casesService.add(created);localStorage.removeItem(draftKey);setStage('done');}
 function removeMessage(id:string){setMessages(current=>current.filter(message=>message.id!==id));}
 if(stage==='welcome') return <main className="public-shell"><section className="public-card welcome"><div className="brand-mark">CZ</div><p className="eyebrow">{lawyer.firm}</p><h1>Pré-atendimento<br/>inteligente.</h1><p className="lead">Conte rapidamente o que aconteceu. O CasoZero organiza as informações antes da análise do escritório.</p><div className="time"><MessageCircle size={17}/> Leva aproximadamente 3 minutos</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Concordo que as informações fornecidas sejam utilizadas pelo escritório para análise deste pré-atendimento.</span></label><button className="primary" disabled={!consent} onClick={begin}>Começar pré-atendimento <ArrowRight size={18}/></button><p className="fineprint">Este atendimento não substitui orientação jurídica profissional.<br/><a href="#">Política de Privacidade</a> · <a href="#">Termos de Uso</a></p></section></main>;
 if(stage==='profile') return <main className="public-shell"><section className="public-card profile-step"><p className="eyebrow">Antes de começar</p><h1>Vamos conhecer você.</h1><p className="lead">Essas informações ajudam o escritório a organizar seu atendimento.</p><label className="field">Nome completo<input autoFocus value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="Como podemos chamar você?"/></label><label className="field">Idade<input type="number" min="1" max="120" value={profile.age} onChange={e=>setProfile({...profile,age:e.target.value})} placeholder="Sua idade"/></label><label className="field">Profissão<input value={profile.profession} onChange={e=>setProfile({...profile,profession:e.target.value})} placeholder="Ex.: Assistente administrativo"/></label><label className="field">Telefone para contato<input type="tel" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})} placeholder="(00) 00000-0000"/></label><label className="field">Empresa onde trabalha<input value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})} placeholder="Opcional"/></label><label className="field">Faixa salarial<select value={profile.salary} onChange={e=>setProfile({...profile,salary:e.target.value})}><option value="">Opcional</option><option>Entre R$ 1.000,00 e R$ 2.000,00</option><option>Entre R$ 2.000,00 e R$ 5.000,00</option><option>Entre R$ 5.000,00 e R$ 10.000,00</option><option>Mais de R$ 10.000,00</option></select></label><button className="primary" disabled={!profile.name||!profile.age||!profile.profession||!profile.phone} onClick={beginInterview}>Continuar <ArrowRight size={18}/></button><p className="fineprint">Seu telefone será encaminhado ao escritório para retorno, se necessário.</p></section></main>;
 if(stage==='review') return <main className="public-shell"><section className="public-card completion"><p className="eyebrow">Última revisão</p><h1>Confira suas informações.</h1><div className="review-facts"><div><span>Nome</span><strong>{profile.name}</strong></div><div><span>Idade</span><strong>{profile.age} anos</strong></div><div><span>Profissão</span><strong>{profile.profession}</strong></div><div><span>Telefone</span><strong>{profile.phone}</strong></div></div><p className="lead">A conversa será encaminhada para análise do escritório.</p><button className="primary" onClick={()=>finish(state)}>Enviar pré-atendimento <ArrowRight size={18}/></button><button className="secondary" onClick={()=>setStage('chat')}>Voltar e revisar conversa</button></section></main>;
 if(stage==='done') return <main className="public-shell"><section className="public-card completion"><div className="success"><Check size={30}/></div><p className="eyebrow">Pré-atendimento enviado</p><h1>Pronto! Organizamos as principais informações do seu relato.</h1><p className="lead">Seu pré-atendimento foi encaminhado para análise do escritório. Caso necessário, entraremos em contato.</p><div className="case-code">CZ-2026-00{Math.floor(Math.random()*900+100)}</div><button className="secondary" onClick={()=>setStage('welcome')}>Finalizar</button><p className="fineprint">O CasoZero é uma ferramenta de organização e não fornece aconselhamento jurídico.</p></section></main>;
 function attach(event: React.ChangeEvent<HTMLInputElement>) { const file=event.target.files?.[0]; if(file) setMessages(current=>[...current,{id:crypto.randomUUID(),role:'user',content:`Documento anexado: ${file.name}`,createdAt:'Agora'}]); }
 return <main className="chat-shell"><header className="chat-header"><div><div className="avatar">CZ</div><div><strong>CasoZero</strong><span>{lawyer.firm}</span></div></div><Link href="/app">Área do advogado</Link></header><section className="chat"><div className="progress"><span>{hint}</span><i><b style={{width:`${progress}%`}}/></i></div><div className="messages">{messages.map(m=><div key={m.id} className={`message-wrap ${m.role}`}><div className={`bubble ${m.role}`}><p>{m.content}</p><small>{m.createdAt}</small></div><button className="delete-message" onClick={()=>removeMessage(m.id)} aria-label="Apagar mensagem" title="Apagar mensagem"><Trash2 size={13}/></button></div>)}{loading&&<div className="bubble assistant thinking"><Loader2 size={16}/> Organizando sua resposta...</div>}</div><div className="composer"><label className="attach" aria-label="Anexar documento" title="Anexar documento"><Paperclip size={20}/><input type="file" accept=".pdf,.jpg,.jpeg,.png,.docx" onChange={attach}/></label><input aria-label="Sua resposta" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Digite sua resposta"/><button className="send" onClick={()=>send()} aria-label="Enviar"><ArrowRight size={19}/></button></div><div className="quick"><button onClick={()=>send('Sim')}>Sim</button><button onClick={()=>send('Não')}>Não</button><button onClick={()=>send('Não sei informar')}>Não sei informar</button></div><p className="chat-disclaimer">As informações serão encaminhadas ao escritório para análise. Não há aconselhamento jurídico nesta conversa.</p></section></main>;
}



