import Link from 'next/link';
import { ArrowRight, Check, MessageCircle, Sparkles, Waypoints } from 'lucide-react';

export default function Home() {
  return <main className="landing">
    <nav className="landing-inline-nav"><Link href="/" className="landing-wordmark">CasoZero</Link><div className="landing-links"><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><div className="landing-nav-actions"><Link href="/app" className="login-link">Entrar</Link><Link href="/precos" className="primary small">Começar agora <ArrowRight size={15}/></Link></div></nav>
    <section className="landing-hero landing-video-hero" aria-label="Apresentação do CasoZero"><video src="/casozero/casozero-intro.mp4" autoPlay muted loop playsInline /></section>
    <section id="como-funciona" className="landing-section process-section"><div className="section-heading"><p className="eyebrow">Como funciona</p><h2>Do primeiro contato<br/><em>à próxima decisão.</em></h2><p>Uma base flexível para diferentes áreas, com a mesma lógica simples.</p></div><div className="process-steps"><div><span>01</span><h3>Compartilhe seu canal</h3><p>Um link para site, WhatsApp, redes sociais ou QR Code.</p></div><Waypoints className="step-arrow" size={22}/><div><span>02</span><h3>A pessoa explica</h3><p>Uma conversa acolhedora coleta contexto, dados e necessidades.</p></div><Waypoints className="step-arrow" size={22}/><div><span>03</span><h3>Você atende melhor</h3><p>O painel entrega uma visão clara para preparar o próximo passo.</p></div></div></section>
    <section id="recursos" className="landing-section resource-section"><div className="section-heading centered"><p className="eyebrow">Uma nova rotina</p><h2>Menos retrabalho.<br/><em>Mais presença no atendimento.</em></h2></div><div className="benefit-grid"><article className="benefit-card"><MessageCircle size={21}/><h3>Conversa estruturada</h3><p>O cliente fala com naturalidade e você recebe as informações organizadas.</p></article><article className="benefit-card"><Sparkles size={21}/><h3>Experiência inteligente</h3><p>Perguntas e fluxos adaptáveis ao contexto de cada profissão.</p></article><article className="benefit-card"><Check size={21}/><h3>Próximos passos claros</h3><p>Casos, agenda, documentos e histórico em uma única visão.</p></article></div></section>
    <section id="planos" className="landing-cta"><div><p className="eyebrow">Uma plataforma para crescer com você</p><h2>Seu trabalho é único.<br/><em>Seu sistema também pode ser.</em></h2><p>Comece agora e adapte o CasoZero à sua área de atuação.</p><Link href="/precos" className="primary hero-button">Ver planos <ArrowRight size={17}/></Link></div></section>
    <footer className="landing-footer"><Link href="/" className="landing-wordmark">CasoZero</Link><p>Contexto melhor para cada atendimento.</p><small>© 2026 CasoZero</small></footer>
  </main>;
}
