import Link from 'next/link';
import { ArrowRight, Check, ChevronDown, Clock3, FileText, Filter, Menu, MessageCircle, ShieldCheck, Sparkles, Waypoints } from 'lucide-react';

const benefits = [
  { icon: MessageCircle, title: 'Converse com quem chegou', text: 'Seu potencial cliente conta o que aconteceu em uma experiência leve, sem formulário interminável.' },
  { icon: Filter, title: 'Filtre o que importa', text: 'O CasoZero organiza cada relato e mostra o que merece a sua atenção primeiro.' },
  { icon: FileText, title: 'Receba casos prontos', text: 'Resumo, temas, cronologia, documentos e informações ausentes em uma única visão.' },
];
const plans = [{ name: 'CasoUm', price: '79,90', description: 'Para começar a organizar seus pré-atendimentos.', highlight: '1 advogado · 50 atendimentos/mês' }, { name: 'CasoDois', price: '129,90', description: 'Para transformar o pré-atendimento em parte da sua operação.', highlight: '1 advogado · 200 atendimentos/mês', featured: true }, { name: 'CasoTres', price: '499,90', description: 'Para escritórios que trabalham em equipe.', highlight: 'Até 10 advogados · 1.000 atendimentos/mês' }];

export default function Home() { return <main className="landing"><nav className="landing-nav"><Link href="/" className="landing-logo"><span>CZ</span><b>CasoZero</b></Link><div className="landing-links"><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></div><div className="landing-nav-actions"><Link href="/app" className="login-link">Entrar</Link><Link href="/precos" className="primary small">Começar agora <ArrowRight size={15}/></Link></div><button className="landing-menu" aria-label="Abrir menu"><Menu size={20}/></button></nav>
  <section className="landing-hero"><div className="hero-copy"><div className="hero-kicker"><span className="pulse-dot"/> Pré-atendimento inteligente para advocacia</div><h1>Antes da consulta,<br/><em>organize o caso.</em></h1><p>O CasoZero conversa com seus potenciais clientes, estrutura cada relato e entrega para você somente o que precisa de análise.</p><div className="hero-actions"><Link href="/muriloguedes" className="primary hero-button">Ver como funciona <ArrowRight size={17}/></Link><a href="#como-funciona" className="text-action">Conhecer o CasoZero <ChevronDown size={16}/></a></div><div className="hero-note"><ShieldCheck size={16}/> Mais clareza para você. Menos espera para o cliente.</div></div><div className="hero-visual"><div className="glow"/><div className="floating-card card-top"><span className="tiny-label">NOVO PRÉ-ATENDIMENTO</span><strong>Maria Santos</strong><small>Trabalhista · Horas extras</small><div className="card-status"><i/> Alta compatibilidade <ArrowRight size={13}/></div></div><div className="phone-mock"><div className="phone-bar"><div className="phone-avatar">CZ</div><div><b>CasoZero</b><small>Guedes Advocacia</small></div><span>•••</span></div><div className="chat-time">AGORA</div><div className="mock-message assistant">Olá, Maria. Para começar, conte em poucas palavras o que aconteceu.<small>14:20</small></div><div className="mock-message user">Trabalhei durante 3 anos em uma empresa e fui demitida. Acho que minhas horas extras não foram pagas.<small>14:21</small></div><div className="mock-message assistant typing"><i/><i/><i/></div><div className="mock-input">Digite sua resposta <span>↑</span></div></div><div className="floating-card card-bottom"><div className="mini-check"><Check size={14}/></div><div><strong>Informações organizadas</strong><small>Resumo pronto para análise</small></div></div></div></section>
  <section className="proof-strip"><div><strong>24h</strong><span>Disponível para<br/>novos atendimentos</span></div><div><strong>5–8</strong><span>Perguntas de alto<br/>valor de informação</span></div><div><strong>1</strong><span>Visão clara para<br/>cada potencial caso</span></div><div><ShieldCheck size={24}/><span>Feito para respeitar<br/>a sua prática</span></div></section>
  <section id="como-funciona" className="landing-section process-section"><div className="section-heading"><p className="eyebrow">Como funciona</p><h2>Do primeiro relato<br/><em>à próxima decisão.</em></h2><p>O CasoZero tira o peso do pré-atendimento sem tirar de você a decisão que realmente importa.</p></div><div className="process-steps"><div><span>01</span><h3>Compartilhe seu link</h3><p>Um endereço simples para colocar no WhatsApp, Instagram, site ou QR Code.</p></div><Waypoints className="step-arrow" size={22}/><div><span>02</span><h3>O cliente conta</h3><p>Uma conversa acolhedora coleta nome, contexto e as informações essenciais.</p></div><Waypoints className="step-arrow" size={22}/><div><span>03</span><h3>Você analisa</h3><p>Um caso organizado chega ao seu painel, pronto para a sua avaliação humana.</p></div></div></section>
  <section id="recursos" className="landing-section resource-section"><div className="section-heading centered"><p className="eyebrow">Uma nova rotina</p><h2>Menos conversa repetida.<br/><em>Mais tempo para advogar.</em></h2></div><div className="benefit-grid">{benefits.map(({icon:Icon,title,text})=><article className="benefit-card" key={title}><div className="benefit-icon"><Icon size={20}/></div><h3>{title}</h3><p>{text}</p><a href="#planos">Saiba mais <ArrowRight size={14}/></a></article>)}</div><div className="feature-banner"><div><p className="eyebrow">Uma visão, não uma caixa de entrada</p><h3>Chegue ao trabalho sabendo<br/><em>o que aconteceu.</em></h3><p>Compatibilidade, informações faltantes e histórico completo. Tudo no mesmo lugar.</p><Link href="/app" className="secondary small">Explorar painel <ArrowRight size={15}/></Link></div><div className="dashboard-preview"><div className="preview-head"><span>Hoje</span><strong>8 novos pré-atendimentos</strong></div><div className="preview-row"><div className="preview-avatar">MS</div><div><b>Maria Santos</b><small>Trabalhista · Horas extras / Rescisão</small></div><span>Alta</span></div><div className="preview-row"><div className="preview-avatar yellow">JO</div><div><b>João Oliveira</b><small>Consumidor · Cobrança indevida</small></div><span>Alta</span></div><div className="preview-row faded"><div className="preview-avatar">AC</div><div><b>Ana Costa</b><small>Trabalhista · Assédio</small></div><span>Média</span></div></div></div></section>
  <section id="planos" className="landing-section plans-section"><div className="section-heading centered"><p className="eyebrow">Escolha o seu momento</p><h2>Um CasoZero para cada<br/><em>fase da sua advocacia.</em></h2><p>Comece simples e evolua conforme sua operação cresce.</p></div><div className="plans-grid">{plans.map(plan=><article className={`landing-plan ${plan.featured?'featured':''}`} key={plan.name}>{plan.featured&&<div className="most-chosen">Mais escolhido</div>}<p className="plan-name">{plan.name}</p><p className="plan-description">{plan.description}</p><div className="plan-price"><sup>R$</sup><strong>{plan.price}</strong><span>/mês</span></div><p className="plan-highlight"><Check size={15}/>{plan.highlight}</p><Link href="/precos" className={plan.featured?'primary small':'secondary small'}>Conhecer plano <ArrowRight size={14}/></Link></article>)}</div><p className="plans-footnote"><Sparkles size={14}/> Todos os planos têm a mesma inteligência principal. Sem cartão no teste.</p></section>
  <section className="landing-cta"><div><p className="eyebrow">Seu próximo atendimento pode começar agora</p><h2>Organize o caso.<br/><em>Ganhe clareza.</em></h2><p>Teste com seus primeiros 10 pré-atendimentos.</p><Link href="/precos" className="primary hero-button">Começar gratuitamente <ArrowRight size={17}/></Link></div><div className="cta-orb"><Clock3 size={26}/><span>Leva aproximadamente<br/><b>3 minutos</b></span></div></section>
  <footer className="landing-footer"><Link href="/" className="landing-logo"><span>CZ</span><b>CasoZero</b></Link><p>Antes da consulta, deixe o CasoZero organizar o caso.</p><div><a href="#recursos">Recursos</a><a href="#planos">Planos</a><Link href="/app">Entrar</Link></div><small>© 2026 CasoZero · Atendimento realizado com CasoZero</small></footer></main>; }
